export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const FORGOT_PASSWORD_USER_REQUEST = "FORGOT_PASSWORD_USER_REQUEST";
export const FORGOT_PASSWORD_USER_SUCCESS = "FORGOT_PASSWORD_USER_SUCCESS";
export const FORGOT_PASSWORD_USER_FAIL = "FORGOT_PASSWORD_USER_FAIL";

export const RESET_PASSWORD_USER_REQUEST = "RESET_PASSWORD_USER_REQUEST";
export const RESET_PASSWORD_USER_SUCCESS = "RESET_PASSWORD_USER_SUCCESS";
export const RESET_PASSWORD_USER_FAIL = "RESET_PASSWORD_USER_FAIL";

export const UPDATE_PASSWORD_USER_REQUEST = "UPDATE_PASSWORD_USER_REQUEST";
export const UPDATE_PASSWORD_USER_SUCCESS = "UPDATE_PASSWORD_USER_SUCCESS";
export const UPDATE_PASSWORD_USER_FAIL = "UPDATE_PASSWORD_USER_FAIL";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const PROFILE_USER_REQUEST = "PROFILE_USER_REQUEST";
export const PROFILE_USER_SUCCESS = "PROFILE_USER_SUCCESS";
export const PROFILE_USER_FAIL = "PROFILE_USER_FAIL";

export const PROFILE_UPDATE_USER_REQUEST = "PROFILE_UPDATE_USER_REQUEST";
export const PROFILE_UPDATE_USER_SUCCESS = "PROFILE_UPDATE_USER_SUCCESS";
export const PROFILE_UPDATE_USER_FAIL = "PROFILE_UPDATE_USER_FAIL";
